### ISSUE TITLE
sslv3 alert handshake failure on v0.5

### ISSUE THREAD

**Issue by karlbright** [buildkite/buildbox-agent-ruby#10]
New Digitalocean box.
- git clone rbenv + setup with bash_profile
- git clone ruby-build
- sudo apt-get install build-essential zlib1g-dev libreadline-dev libssl-dev libcurl4-openssl-dev
- rbenv install 1.9.3-p448
- rbenv global 1.9.3-p448
- ruby -v to check 1.9.3-p448 was being used
- gem install buildbox
- rbenv rehash
- buildbox agent:setup <ACCESS TOKEN>
- buildbox agent:start

```
karl@wellington-lingerie:~$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04 LTS
Release:    12.04
Codename:   precise
```

```
Buildbox::API::ServerError: SSL_connect returned=1 errno=0 state=unknown state: sslv3 alert handshake failure
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:800:in `connect'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:800:in `connect'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:745:in `start'
    /home/karl/.rbenv/versions/1.9.3-p448/lib/ruby/1.9.1/net/http.rb:1285:in `request'
```

Openssl version

```
karl@wellington-lingerie:~$ openssl version
OpenSSL 1.0.1 14 Mar 2012
```

**Comment by karlbright** [comment]
Also tried the following:

```
export CONFIGURE_OPTS="--with-openssl-dir=/usr/bin/openssl"
rbenv install 1.9.3-p448
```

but no luck.

**Comment by karlbright** [comment]
Had a look over https://gist.github.com/mhutter/1682948 but had no luck after ensuring i had the packages installed and although my openssl is not at /usr/local i tried it anyway via CONFIGURE_OPTS as passing it to rbenv install does not work

**Comment by karlbright** [comment]
```
RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr" rbenv install 1.9.3-p448
```

Without CONFIGURE_OPTS set. No luck

**Comment by keithpitt** [comment]
Seen this? http://railsapps.github.io/openssl-certificate-verify-failed.html

**Comment by karlbright** [comment]
Got it solved.

Added `deb http://archive.ubuntu.com/ubuntu/ precise-proposed restricted main multiverse universe` to /etc/apt/sources.list via https://wiki.ubuntu.com/Testing/EnableProposed

Updated to https://launchpad.net/ubuntu/+source/openssl/1.0.1-4ubuntu5 from 1.0.1-4ubuntu3
